sonar.projectKey=cifradorM
sonar.projectName=cifradorM
sonar.sources=.
sonar.java.binaries=target/classes,android/app/build/tmp/kotlin-classes/debug,android/app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/.build/**,**/.git/**,**/.mvn/local-repo/**,ejecuciones.sh
